Traceback (most recent call last):
  File "d:\scientific_research\SelfCode\Spatio_Temporal_Neural_Network\PINNacle-fork2test\run_experiment_burgers1d_standard_fnn.py", line 64, in <module>
    trainer.train_all()
  File "d:\scientific_research\SelfCode\Spatio_Temporal_Neural_Network\PINNacle-fork2test\trainer.py", line 98, in train_all
    model = get_model()
            ^^^^^^^^^^^
  File "d:\scientific_research\SelfCode\Spatio_Temporal_Neural_Network\PINNacle-fork2test\run_experiment_burgers1d_standard_fnn.py", line 22, in get_model
    pde = Burgers1D(
          ^^^^^^^^^^
  File "d:\scientific_research\SelfCode\Spatio_Temporal_Neural_Network\PINNacle-fork2test\src\pde\burgers.py", line 31, in __init__
    self.load_ref_data(datapath)
  File "d:\scientific_research\SelfCode\Spatio_Temporal_Neural_Network\PINNacle-fork2test\src\pde\baseclass.py", line 213, in load_ref_data
    super(BaseTimePDE, self).load_ref_data(datapath, transform_fn, t_transpose)
  File "d:\scientific_research\SelfCode\Spatio_Temporal_Neural_Network\PINNacle-fork2test\src\pde\baseclass.py", line 92, in load_ref_data
    self.ref_data = np.loadtxt(datapath, comments="%", encoding='utf-8').astype(np.float32)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chrisv\.conda\envs\ml_torch\Lib\site-packages\numpy\lib\_npyio_impl.py", line 1381, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chrisv\.conda\envs\ml_torch\Lib\site-packages\numpy\lib\_npyio_impl.py", line 1021, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 190-191: invalid continuation byte
